baseURL = "https://rjfranssen.io/"
title = "rjfranssen"
enableRobotsTXT = true
theme = "compose"
enableGitInfo = true
enableEmoji = true # added this
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.yml$",] # added this per blogdown recommendation

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks] # added this for new blog posts per blogdown recommendation
    post = "/:year/:month/:day/:slug/"
    
#  menu items
#[[menu.main]]
#    name = "Docs"
#    weight = 1
#    url = "docs/"

[[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

[[menu.main]]
    name = "Posts"
    weight = 2
    url = "post/"
    
[[menu.main]]
    name = "Apps"
    weight = 3
    url = "app/"

[[menu.main]]
    name = "Links"
    weight = 4
    url = "links/list/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Everything below this are Site Params

[params]
  author = "rjfranssen"
  searchPlaceholder = "Search..."
  repo = "https://github.com/rjfranssen/rjfranssen.github.io"

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = false # set to false to disable darkmode by default # user will still have the option to use dark mode
  [params.logo]
    lightMode = "rjfranssen-blowfish-wide-dark.png"
    darkMode = "rjfranssen-blowfish-wide-dark.png"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/rjfranssen/rjfranssen.github.io"
